export default [
        {
                id: 1,
                header: "Basic T-Shirt (White)",
                type: "Apparel",
                status: "In Stock",
                target: "200",
                limit: "50",
                reviewer: "Sandiaga",
        },
        {
                id: 2,
                header: "Denim Jacket",
                type: "Outerwear",
                status: "Low Stock",
                target: "50",
                limit: "10",
                reviewer: "Budi",
        },
        {
                id: 3,
                header: "Chino Pants (Black)",
                type: "Pants",
                status: "In Stock",
                target: "150",
                limit: "30",
                reviewer: "Ani",
        },
        {
                id: 4,
                header: "Summer Dress",
                type: "Dress",
                status: "In Stock",
                target: "100",
                limit: "20",
                reviewer: "Sandiaga",
        },
        {
                id: 5,
                header: "Hoodie (Grey)",
                type: "Apparel",
                status: "Out of Stock",
                target: "80",
                limit: "0",
                reviewer: "Budi",
        },
        {
                id: 6,
                header: "Leather Belt",
                type: "Accessory",
                status: "In Stock",
                target: "300",
                limit: "100",
                reviewer: "Ani",
        },
];
